name: LEM_environment
channels:
  - conda-forge
dependencies:
  - python=3.12.8
  - numpy=1.26.4
  - scipy=1.14.1
  - matplotlib=3.10.0
  - watermark=2.5.0
  - gdal=3.10.0
  - richdem=2.3.0
  - landlab=2.9.2
